const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Touch,
		C3.Plugins.Mouse,
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Behaviors.DragnDrop,
		C3.Behaviors.Tween,
		C3.Plugins.Arr,
		C3.Behaviors.Rotate,
		C3.Behaviors.Flash,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Mouse.Acts.SetCursor,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.Browser.Acts.CancelFullScreen,
		C3.Plugins.Audio.Acts.SetPaused,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Arr.Exps.Back,
		C3.Plugins.Sprite.Exps.AnimationFrameTag,
		C3.Plugins.Audio.Acts.SetVolume,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.While,
		C3.Plugins.Arr.Cnds.CompareSize,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Arr.Cnds.Contains,
		C3.Plugins.Arr.Acts.Push,
		C3.Plugins.System.Exps.tokencount,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Arr.Exps.Front,
		C3.Plugins.Arr.Acts.Pop,
		C3.Plugins.System.Exps.tokenat,
		C3.Behaviors.DragnDrop.Cnds.OnDragStart,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Behaviors.DragnDrop.Cnds.OnDrop,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.System.Acts.AddVar,
		C3.Behaviors.DragnDrop.Acts.SetEnabled,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.Wait,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Arr.Cnds.IsEmpty,
		C3.Plugins.System.Cnds.OnLayoutEnd
	];
};
self.C3_JsPropNameTable = [
	{btnBasla: 0},
	{btnBilgi: 0},
	{kapla: 0},
	{btnFullScreen: 0},
	{btnHazirlayanlar: 0},
	{btnHome: 0},
	{btnKaynakca: 0},
	{durum: 0},
	{btnMuzik: 0},
	{btnSes: 0},
	{btnButon: 0},
	{btnKapat: 0},
	{devam: 0},
	{Touch: 0},
	{Mouse: 0},
	{Audio: 0},
	{Browser: 0},
	{gameBackground: 0},
	{home: 0},
	{bilgiEkran: 0},
	{hazirlayanlar: 0},
	{kaynakca: 0},
	{butonlarEkran: 0},
	{m: 0},
	{n: 0},
	{DragDrop: 0},
	{Tween: 0},
	{protein: 0},
	{listeharf: 0},
	{a: 0},
	{b: 0},
	{kutu: 0},
	{sorular: 0},
	{sorudiz: 0},
	{tebrikler: 0},
	{Rotate: 0},
	{Sprite: 0},
	{btnTekrarOyna: 0},
	{Flash: 0},
	{dogruTik: 0},
	{butonlar: 0},
	{muzikdurum: 0},
	{rastsay: 0},
	{dogru: 0},
	{cevap: 0},
	{kelime: 0}
];

self.InstanceType = {
	btnBasla: class extends self.ISpriteInstance {},
	btnBilgi: class extends self.ISpriteInstance {},
	btnFullScreen: class extends self.ISpriteInstance {},
	btnHazirlayanlar: class extends self.ISpriteInstance {},
	btnHome: class extends self.ISpriteInstance {},
	btnKaynakca: class extends self.ISpriteInstance {},
	btnMuzik: class extends self.ISpriteInstance {},
	btnSes: class extends self.ISpriteInstance {},
	btnButon: class extends self.ISpriteInstance {},
	btnKapat: class extends self.ISpriteInstance {},
	devam: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	gameBackground: class extends self.ISpriteInstance {},
	home: class extends self.ISpriteInstance {},
	bilgiEkran: class extends self.ISpriteInstance {},
	hazirlayanlar: class extends self.ISpriteInstance {},
	kaynakca: class extends self.ISpriteInstance {},
	butonlarEkran: class extends self.ISpriteInstance {},
	protein: class extends self.ISpriteInstance {},
	listeharf: class extends self.IArrayInstance {},
	kutu: class extends self.ISpriteInstance {},
	sorular: class extends self.ISpriteInstance {},
	sorudiz: class extends self.IArrayInstance {},
	tebrikler: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	btnTekrarOyna: class extends self.ISpriteInstance {},
	dogruTik: class extends self.ISpriteInstance {},
	butonlar: class extends self.ISpriteInstance {}
}